### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for UPT: size mismatch for dino_cache: copying a param with shape torch.Size([2048, 117]) from checkpoint, the shape in current model is torch.Size([2048, 229]). 

### ISSUE THREAD

**Issue by markryanwww** [soberguo/HOIGen#1]
Hello, thank you very much for your excellent work. I encountered some issues while reproducing your project. First, 
I modified args.dino_load_cache=False in main_tip_finetune.py to ensure that cache is generated in the ./cache/dataset directory. However, after completing the training, I faced a size mismatch issue during evaluation: RuntimeError: Error(s) in loading state_dict for UPT: size mismatch for dino_cache: copying a param with shape torch.Size([2048, 117]) from checkpoint, the shape in current model is torch.Size([2048, 229]).But when I download your pre-trained checkpoint for evaluation, there is no error. 
I would like to ask how to resolve the model size mismatch issue. Looking forward to your reply.

**Comment by soberguo** [comment]
Thank you for your interest in our work. I re-ran the program and did not encounter any issues. I suspect the problem might be due to a change in the num_shot parameter—it should be set to 2. If the issue persists, I can provide our pre-trained DINO cache to assist you.

**Comment by markryanwww** [comment]
Thank you for your timely response! Yes, the issue was indeed due to the num_shot causing a mismatch in feature dimensions and I have solved this issue. Additionally, I have another question: for the dino_model, you recommend using dino_resnet50_pretrained.pth. I found that using the pretrained vit-base16.pth also yields good results, though it does have some missed keys. Overall, do you still prefer the ResNet50 model? Thank you again for your excellent work; it has been very beneficial to me.

**Comment by soberguo** [comment]
Certainly, you can choose different backbones based on your own preferences. In general, larger models tend to deliver better performance. Personally, I opt for ResNet-50 because it helps save memory, which is crucial for my train.

**Comment by markryanwww** [comment]
Thank you for your assistance,I appreciate that.
