### ISSUE TITLE
zero-shot setting

### ISSUE THREAD

**Issue by xx-dd-xx** [soberguo/HOIGen#2]
Great job, but I have a question. If the number of output categories is 117(verb's number), is this considered  zero-shot detection? Under UC/UO setting, the training sample contains all verb categories. What is the result when the number of output categories is set to 600(interaction's number)?

**Comment by soberguo** [comment]
Our research builds on prior work, where object detection is completed in the first stage, leaving only classification for the second stage. Consequently, the classification head for the HICO-DET dataset has 117 classes.
