### ISSUE TITLE
where can I get dino_keys_2shots.pt

### ISSUE THREAD

**Issue by safsfsvvea** [soberguo/HOIGen#3]
Thank you very much for your contribution. When I try to run in the fully supervised settings, the code try to build_dino_cache_model and dino_keys_2shots.pt is needed. But I can't find the file in the repo.

**Comment by soberguo** [comment]
Thank you for your interest in our work. Currently, the .pt files mentioned are not provided. However, we plan to consider uploading them in the future. In the meantime, you can perform the training yourself by setting lines 395 and 396 in the main file to False.
