### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by YangJae96** [soberguo/HOIGen#4]
Hi. Thank you for great work!

Could you provide the code that can inference on a single image?

Its hard to tune the test script code.

**Comment by soberguo** [comment]
Apologies for the delayed response; I am currently working to meet a deadline. The model includes inference code designed for the entire test set. At this time, I do not plan to provide code specifically for single-image inference. However, you can adapt the existing code to suit your needs. I trust that you’ll be able to handle it effectively.
